name: Release Version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java Maven release
        uses: qcastel/github-actions-maven-release@v1.0.3
        with:
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@microsphere.io"
          release-branch-name: "main"

          maven-args: "--batch-mode --update-snapshots -e -P release -Dmaven.plugin.validation=VERBOSE -Drevision=0.0.1-SNAPSHOT clean deploy"
          maven-servers: ${{ secrets.MVN_REPO_SERVERS }}

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}